# Generated by Django 4.1.3 on 2023-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0002_addcategorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('Quality', models.IntegerField()),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
    ]
