# Generated by Django 4.1.3 on 2023-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0003_productdetailsdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailsdb',
            name='Quality',
        ),
        migrations.AddField(
            model_name='productdetailsdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
